global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'aja_encoders'
    static_configs:
      - targets: ['api:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    metric_relabel_configs:
      - source_labels: [encoder_name]
        target_label: instance
  - job_name: 'connection_metrics'
    static_configs:
      - targets: ['api:5000']
    metrics_path: '/metrics/connection'
    scrape_interval: 10s 