version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: 

  #docker-compose up -d

# - Ensure your application is configured to connect to the PostgreSQL database using the connection details specified in the `docker-compose.yml` file. Update your `settings.DATABASE_URL` in your configuration to match these details.