version: "1.0"
requirements:
  - Flask>=2.0.0
  - SQLAlchemy>=1.4.0
  - python-telegram-bot>=20.7
  - gunicorn==21.2.0
  - prometheus-client>=0.17.1
  - psycopg2-binary>=2.9.9
  - alembic>=1.12.1
  - pydantic>=2.5.2
  - Flask-Limiter>=3.5.0
  - Flask-Caching>=2.1.0
  - redis>=5.0.1

directories:
  - app/api
  - app/core
  - app/models
  - app/services
  - app/static/js
  - app/static/css
  - app/templates
  - app/tests
  - app/migrations
  - logs
  - config

database:
  url: "postgresql://localhost/encoder_manager"
  
monitoring:
  prometheus_port: 9090
  grafana_port: 3000

security:
  ssl_cert_path: "/etc/letsencrypt/live/your-domain/fullchain.pem"
  ssl_key_path: "/etc/letsencrypt/live/your-domain/privkey.pem" 