version: "1.0"
requirements:
  - Flask==2.3.3
  - SQLAlchemy==2.0.36
  - python-telegram-bot>=20.7
  - gunicorn==21.2.0
  - prometheus-client==0.21.1
  - psycopg2-binary==2.9.9
  - alembic==1.14.0

  - pydantic==2.4.2
  - Flask-Limiter==3.5.0
  - Flask-Caching==2.1.0
  - redis==5.0.1
  - rq==1.15.1
  - Flask-Session==0.5.0
  - Flask-SocketIO==5.3.6
  - python-dotenv>=1.0.0
  - structlog==23.1.0
  - pytest==7.4.3
  - pytest-cov==4.1.0
  - pytest-mock==3.11.0

directories:
  - app/api
  - app/core
  - app/models
  - app/services
  - app/static/js
  - app/static/css
  - app/templates
  - app/tests
  - app/migrations
  - logs
  - config

database:
  url: "postgresql://localhost/encoder_manager"
  
monitoring:
  prometheus_port: 9090
  grafana_port: 3000

security:
  ssl_cert_path: "/etc/letsencrypt/live/your-domain/fullchain.pem"
  ssl_key_path: "/etc/letsencrypt/live/your-domain/privkey.pem" 