version: '3.9'

services:
  db:
    image: postgres:15
    container_name: watchtower_postgres
    restart: always
    environment:
      POSTGRES_DB: watchtower
      POSTGRES_USER: watchuser
      POSTGRES_PASSWORD: watchpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: watchtower_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - "8080:80"
    depends_on:
      - db

  backend:
    build: ./backend
    container_name: watchtower_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://watchuser:watchpass@db:5432/watchtower
    depends_on:
      - db

volumes:
  pgdata:
