global:
  resolve_timeout: 5m
  telegram_api_url: 'https://api.telegram.org'
  telegram_bot_token: '${TELEGRAM_BOT_TOKEN}'

route:
  group_by: ['alertname', 'encoder_name']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'telegram-alerts'

receivers:
  - name: 'telegram-alerts'
    telegram_configs:
      - bot_token: '${TELEGRAM_BOT_TOKEN}'
        chat_id: ${TELEGRAM_CHAT_ID}
        parse_mode: 'HTML'
        message: |
          🚨 <b>{{ .GroupLabels.alertname }}</b>
          
          <b>Encoder:</b> {{ .Labels.encoder_name }}
          <b>Severity:</b> {{ .Labels.severity }}
          <b>Status:</b> {{ .Status }}
          
          {{ .Annotations.description }}